camel-salesforce - Add missing test dependency and id (#863)
## Motivation

The test `RawPayloadTest` in `camel-salesforce` fails due to the exception `NoSuchMethodError: 'void okhttp3.internal.Internal.initializeInstanceForTests()'`

## Modifications:

* Adds the missing test dependency based on https://github.com/apache/camel/blob/main/components/camel-salesforce/camel-salesforce-component/pom.xml#L237-L243
* Adds the id to the fake payload response to avoid an NPE when [extracting the `orgId`](https://github.com/apache/camel/blob/main/components/camel-salesforce/camel-salesforce-component/pom.xml#L237-L243)